services:
  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    env_file: .env
    ports:
      - "8001:8000"
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db

volumes:
  postgres_data:
