services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: ./backend
    container_name: api
    image: motfromh-site-api:dev
    env_file: .env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app:/app/app
    expose:
      - "8000"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        NUXT_PUBLIC_API_BASE: http://api:8000/api/v1
    container_name: frontend
    image: motfromh-site-frontend:dev
    env_file: .env
    volumes:
      - ./frontend/src:/app/src
    expose:
      - "3000"
    networks:
      - app-network
    depends_on:
      - api

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "8800:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - api

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
